"""empty message

Revision ID: 9228cade0584
Revises: 
Create Date: 2023-03-27 00:06:46.522584

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9228cade0584"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_currency", sa.String(length=8), nullable=True),
        sa.Column("to_currency", sa.String(length=8), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("converted_value", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("when", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calls")
    # ### end Alembic commands ###
